### ISSUE TITLE
GoT library fails several BCH tests

### ISSUE THREAD

**Issue by nathantaal** [gameoftrades/gameoftrades-library#3]
The library of Game of Trades fails several Better Code Hub test. While I understand why it happens, it's not good to teach students this way of programming. Especially when there own test are failing when they are just extending or overriding the library functionality without having anything added themselves.

**Comment by ctrl-alt-dev** [comment]
Hi Nathan,

You're making two points in one question. 
I'll will answer the first ('why does the library fail some of the Better Code Hub checks') in this reply.

It would seem you're making a fair point :)

So, lets break down the worst violations of the library and find out the reasons behind them.

### Complexity: KaartDisplay.toTile

BCH requires that no method should have more than 5 branch points.

The `toTile` routine that translates the tile type to its corresponding image. For some tiles the surroundings must be taken into account (ZEE).  The cause of complexity are the two switch statements. 

Is this method easy to understand? I think so because it really is just a mapping from a enum to an image coordinate on the tile bitmap. The hardest part to understand is the edge mapping which does not score any complexity points (because there are no conditionals).

Would breaking up this method into shorter methods (like BCH suggests) make it any better? Well first of all, breaking up a `switch` statement into methods is not really possible. The only thing that can be done is make it an `if/else if` and then split it up which would not improve things in terms of readability and complexity. 

It _is_ possible to split the `ZEE` case into a separate method.  Does that bring complexity down to 5? Nope. Does it make it easier to understand? It depends on how you look at it. I find it useful to have the whole tile->image translation table in one place.

Reducing complexity by extracting methods is not a magic bullet. Read ['Small functions considered harmful'](https://medium.com/@copyconstruct/small-functions-considered-harmful-91035d316c29) 

### Unit Interfaces: HandelaarScanner.vindEnInstantieer

Agreed. This private method has 5 arguments which could be easily reduced by making `base` a constant. This would improve the readability of the method.

### Unit Interfaces: HandelsPositie constructor 

BCH requires a method to have at most 4 arguments.

This constructor has 5 arguments that are all required to initialize the object. Removing a parameter is not an option, so the alternative is to use an additional object holding the arguments or even create a builder object for it. I'm not considering setters as that would break the [immutability](https://en.wikipedia.org/wiki/Immutable_object) of the object.

It is possible to create an additional object to hold the constructor arguments. The simplest would be just a collection of fields and their getters and setters. However this is problematic as all fields are mandatory and it would require 5 lines in the calling code (one for each setter).

Would a [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern#Java) be better? Well you could use a fluid syntax and add an all parameters set check which will make the calling code more readable and satisfy the preconditions of the HandelsPositie. At the expense of an additional class of course.

If you take into account the intent of the constructor; which is capturing the initial position of the trader; it is perfect - the 5 arguments represent just what is needed. There are no optional arguments, no variations. Introduction of a parameter object would only obscure that intent.

### Balancing of Architecture Components

In order to make this check work it needs configuration (the depth parameter). If that were the case it would spot an imbalance between the user interface code and the rest of the library. A proper solution would be to split off the user interface code and make it a separate project. However that would increase the complexity of releasing the various parts and managing dependencies which I feel is not worth it.

### Automate Tests

BCH demands that the size (in lines) of the test-code is 50% of the production code. In case of the library that means 2005 / 2 = 1003 lines (the current number of test-code lines is 774). BCH does not measure actual [code coverage](https://dzone.com/articles/an-introduction-to-code-coverage) ; which parts of the production code are covered by the tests.

If you were to use actual coverage you would find that the library itself has really good coverage, but the user interface part does not. Why? You cannot really unit test a user interface without displaying it on the screen, which makes it automatically an integration test.

You could argue that the user interface part should be split into a separate project (see also the previous section) but in this case that would only result in a good and a bad project test wise.

## Conclusion

I hope I've provided some insight in why the library doesn't pass all the tests.

BCH has a set of rules that sound reasonable and are easy to implement and check for. However these rules are not automatically a good measure of quality; for example [the naming of methods and classes](https://www.youtube.com/watch?v=SctS56YQ6fg) are not taken into account.   

So, while BCH is useful as a teaching instrument, you should keep thinking and use your own judgement. 

To prove my point, I think you will find [this project](https://github.com/xanathar-the-beholder/bad-game) interesting.

**Comment by ctrl-alt-dev** [comment]
In the second part of your question you suggest that your project fails because of the library failing the BCH checks. 

_This is not true._ Each project is scored on the code it contains. Not its dependencies.

There may be contamination if the interfaces of the project require you to implement methods with more than 4 arguments (Rule number 4, Unit Interfaces). This is not the case. The maximum number of arguments used is 3. 

I had a brief look at your projects (got18-team28) BCH failures.

### WereldLader.laad

Your teams `WereldLader.laad` consists of 108 lines of code. It combines IO, parsing and construction of the World into one method. It swallows an exception by just printing it. BCH complains on length and complexity of the method and I think this is rightfully so. 

You could improve the WereldLader by making separate objects for IO, parsing and world construction. Or you could follow BCHs advice and split the method into smaller methods.

### Code duplication in Dijkstra and BreadthFirstSearch

It seems your `BreadthFirstSearch` and `Dijkstra` implementations share some code. This is not caused by the library.

You could move this shared code into an abstract base class which can be extended by both implementations.
 
### CustomUI

There is no requirement to write a Custom UI in the assignment. Of course you are free to make one if you want to ;-) I would place this in the test folder.

**Comment by nathantaal** [comment]
That's interesting, I will look into the bad game project tonight. 
I did not recall blaming the library for ~~my code~~ our code failing the tests and when I'm reading my own post, I do not understand why I even blamed the library for that. I know there is lots to be improved, and generally how to do it, but that's not the priority for now ;)
Thanks for the detailed reply, I'll go ahead and close the issue.
